name: Deploy Website on Push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-22.04  # Explicitly specify Ubuntu version
    steps:
      # Step 1: Checkout latest code
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Deploy files via FTP
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 159.65.148.197
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/
          exclude: ".git*"  # Exclude unnecessary files
          dangerous-clean-slate: true  # Remove obsolete files on server
